"""
Django settings for soloyalty project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os


# Import setting depends on the django mode

DJANGO_MODE = os.getenv("DJANGO_MODE", "prod")

if DJANGO_MODE == "prod":
    from .configs.prod import *
elif DJANGO_MODE == "stage":
    from .configs.stage import *
elif DJANGO_MODE == "dev":
    from .configs.dev import *
else:
    raise ValueError("Wrong mode for the Django.")
